#spring.application.name=dubbo-consumer
server:
  port: 8102
  servlet:
    context-path: /dubbo
#应用名称
spring:
  dubbo:
    application:
      name: dubbo-consumer
    #注册中心地址
    protocol:
      name: dubbo
    registry:
      address: zookeeper://127.0.0.1:2181
    #调用dubbo组建扫描的项目路径
#    scan: com.cn.consumer.controller
